# Generated by Django 3.1.1 on 2020-09-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20200929_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_target',
            field=models.IntegerField(),
        ),
    ]
