# Generated by Django 3.1.1 on 2020-09-30 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_auto_20200930_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='user',
        ),
    ]
